TestRunner â€º exceptions in tests
\027[97mexceptions in tests \226\128\186 test framework handling of exceptions\027[39m
\r[3/3] Pending  \027[2m[0/3] Passed\027[22m  \027[2m[0/3] Failed\027[22m\r[2/3] Pending  \027[2m[0/3] Passed\027[22m  \027[31m[1/3] Failed\027[39m\r[1/3] Pending  \027[2m[0/3] Passed\027[22m  \027[31m[2/3] Failed\027[39m\r\027[2m[0/3] Pending\027[22m  \027[2m[0/3] Passed\027[22m  \027[31m[3/3] Failed\027[39m

\027[1m\027[31m  \226\128\162 exceptions in tests \226\128\186 test framework handling of exceptions \226\128\186 normal failure
\027[39m\027[22m    \027[2mexpect.string(\027[22m\027[31mreceived\027[39m\027[2m).toEqual(\027[22m\027[32mexpected\027[39m\027[2m)\027[22m
    
    Expected value to equal:
      \027[32m\"bar\"\027[39m
    Received:
      \027[31m\"foo\"\027[39m
    
    Difference:
      \027[31mfoo\027[39m\027[32mbar\027[39m

\027[1m\027[31m  \226\128\162 exceptions in tests \226\128\186 test framework handling of exceptions \226\128\186 uninlineable exception output\027[39m\027[22m
    Exception \027[2m(Invalid_argument \"I'm invalid :(\")\027[22m

      \027[2m220 \226\148\134 \027[22m\027[2m  expect.\027[22m\027[33m\027[2mstring\027[22m\027[39m\027[2m(\027[22m\027[32m\027[2m\"foo\"\027[22m\027[39m\027[2m).toEqual(\027[22m\027[32m\027[2m\"bar\"\027[22m\027[39m\027[2m)\027[22m
      \027[2m221 \226\148\134 \027[22m\027[2m);\027[22m
      \027[2m222 \226\148\134 \027[22m\027[2mtest(\027[22m\027[32m\027[2m\"uninlineable exception output\"\027[22m\027[39m\027[2m, ({expect})\027[22m\027[31m\027[2m => \027[22m\027[39m\027[2m{\027[22m
      \027[31m\027[2m223 \226\148\134 \027[22m\027[39m\027[2m  \027[22m\027[35m\027[2mlet\027[22m\027[39m\027[2m foo = ()\027[22m\027[31m\027[2m => \027[22m\027[39m\027[31m\027[1m\027[4mraise(Invalid_argument(\"I'm invalid :(\"))\027[24m\027[22m\027[39m\027[2m;\027[22m
      \027[2m224 \226\148\134 \027[22m\027[2m  expect.\027[22m\027[33m\027[2mstring\027[22m\027[39m\027[2m(\027[22m\027[32m\027[2m\"foo\"\027[22m\027[39m\027[2m).toEqual(\027[22m\027[32m\027[2m\"foo\"\027[22m\027[39m\027[2m);\027[22m
      \027[2m225 \226\148\134 \027[22m\027[2m  foo();\027[22m
      \027[2m226 \226\148\134 \027[22m\027[2m});\027[22m

      \027[2mRaised at \027[22m\027[36msrc/test-runner/test/lib/TestRunner_test.re:223:24\027[39m

\027[1m\027[31m  \226\128\162 exceptions in tests \226\128\186 test framework handling of exceptions \226\128\186 inline exception output\027[39m\027[22m
    Exception \027[2mNot_found\027[22m

      \027[2m225 \226\148\134 \027[22m\027[2m  foo();\027[22m
      \027[2m226 \226\148\134 \027[22m\027[2m});\027[22m
      \027[2m227 \226\148\134 \027[22m\027[2mtest(\027[22m\027[32m\027[2m\"inline exception output\"\027[22m\027[39m\027[2m, ({expect})\027[22m\027[31m\027[2m => \027[22m\027[39m\027[2m{\027[22m
      \027[31m\027[2m228 \226\148\134 \027[22m\027[39m\027[2m  \027[22m\027[35m\027[2mlet\027[22m\027[39m\027[2m foo = ()\027[22m\027[31m\027[2m => \027[22m\027[39m\027[31m\027[1m\027[4mraise(Not_found)\027[24m\027[22m\027[39m\027[2m;\027[22m
      \027[2m229 \226\148\134 \027[22m\027[2m  expect.\027[22m\027[33m\027[2mstring\027[22m\027[39m\027[2m(\027[22m\027[32m\027[2m\"foo\"\027[22m\027[39m\027[2m).toEqual(\027[22m\027[32m\027[2m\"foo\"\027[22m\027[39m\027[2m);\027[22m
      \027[2m230 \226\148\134 \027[22m\027[2m  foo();\027[22m
      \027[2m231 \226\148\134 \027[22m\027[2m});\027[22m

      \027[2mRaised at \027[22m\027[36msrc/test-runner/test/lib/TestRunner_test.re:228:24\027[39m\027[2m (inlined)\027[22m
      \027[2mCalled from \027[22m\027[36msrc/test-runner/test/lib/TestRunner_test.re:230:8\027[39m
